create a numpy array using list

In [4]:
import numpy as np

In [ ]:
#1-D array
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [24]:
print(n1.shape)
print(n1.size)

(5,)
5


In [19]:
#2-D array
n2=np.array([[10,20,30,40,50],[1,2,3,4,5]])
n2

array([[10, 20, 30, 40, 50],
       [ 1,  2,  3,  4,  5]])

In [25]:
print(n2.shape)
print(n2.size)

(2, 5)
10


Create two one D arrays each of five elements and apply vector operations like addition, subtraction

In [ ]:
a1=np.array([[1,3,5,7,9],[2,4,6,8,10]])
a2=np.array([[7,8,2,4,6],[9,1,0,5,3]])
print(a1)
print(a2)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[7 8 2 4 6]
 [9 1 0 5 3]]


In [31]:
print(np.add(a1,a2))
print(np.subtract(a1,a2))

[[ 8 11  7 11 15]
 [11  5  6 13 13]]
[[-6 -5  3  3  3]
 [-7  3  6  3  7]]


Zeros

In [38]:
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
c=np.zeros((2,3),dtype=int)
c

array([[0, 0, 0],
       [0, 0, 0]])

matrix with all values ones

In [40]:
c2=np.ones((3,2))
c2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
c2=np.ones((3,2),dtype=int)
c2

array([[1, 1],
       [1, 1],
       [1, 1]])

Create a 3D array of shape (4,3,2) with all zero elements

In [44]:
c3=np.zeros((4,3,2),dtype=int)
c3

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

Create an identity matrix using eye method

In [46]:
c4=np.eye(3)
c4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
p1=np.array([1,2,3,4,5])
p2=np.array([6,7,8,9,10])
print(p1>p2)

[False False False False False]


Apply logical NOT operation on an input array.

In [49]:
c1=np.eye(3,dtype=int)
c2=np.logical_not(c1).astype(int)
print(c2)

[[0 1 1]
 [1 0 1]
 [1 1 0]]


Consider an array of 3 elements. Create deep and shallow copy of this array.

In [50]:
#shallow copy ----> a1.view
#deep copy ----> a1.copy
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
print(a1.view)
print(a2.copy)

<built-in method view of numpy.ndarray object at 0x000002D3FB843210>
<built-in method copy of numpy.ndarray object at 0x000002D3FB72DE90>


In [51]:
x=np.array([5,7,9,3])
x1=x.view
x2=x.copy
print(x1)
print(x2)

<built-in method view of numpy.ndarray object at 0x000002D3FB840FF0>
<built-in method copy of numpy.ndarray object at 0x000002D3FB840FF0>


In [52]:
x=np.array([5,7,9,3])
x1=x+5
print(x1)

[10 12 14  8]


Array re-shape or flatten operating

Create a 2D array of 2x4 and reshape into 4x2.

In [60]:
#reshape operation
x=np.array([[5,7,9,3],[2,4,6,8]])
print(x.reshape(4,2))

[[5 7]
 [9 3]
 [2 4]
 [6 8]]


In [61]:
#flatten operation
x=np.array([[5,7,9,3],[2,4,6,8]])
print(x.ravel())

[5 7 9 3 2 4 6 8]


Indexing and Slicing

Consider an 2D array of 2x4 and 